# Generated by Django 3.2.8 on 2025-12-07 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=10)),
                ('encargado', models.CharField(blank=True, max_length=50, verbose_name='Nombre del Encargado')),
                ('horario', models.CharField(blank=True, default='9:00 - 18:00', max_length=50, verbose_name='Horario de Atención')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Oficina Activa?')),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RFC', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=30)),
                ('apPaterno', models.CharField(max_length=30)),
                ('apMaterno', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('CURP', models.CharField(max_length=14)),
                ('calle', models.CharField(max_length=50)),
                ('colonia', models.CharField(max_length=40)),
                ('municipio', models.CharField(max_length=40)),
                ('CP', models.CharField(max_length=5)),
                ('edad', models.IntegerField(default=0)),
                ('telefono', models.CharField(max_length=10)),
                ('fechaRegistro', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIV', models.CharField(help_text='NIV del vehiculo', max_length=20)),
                ('noMotor', models.CharField(blank=True, max_length=30)),
                ('marca', models.CharField(max_length=40)),
                ('linea', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=4)),
                ('color', models.CharField(default='Blanco', max_length=20, verbose_name='Color del Vehiculo')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Vehiculo Activo?')),
            ],
            options={
                'verbose_name_plural': 'Vehiculos',
                'db_table': 'vehiculos',
            },
        ),
        migrations.CreateModel(
            name='Placa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('numTC', models.CharField(max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estatus', models.BooleanField(default=True)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.oficina')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.propietario')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.vehiculo')),
            ],
        ),
    ]
